import type { Metadata } from "next";
import { inter } from "./ui/fonts";
import AdminLayoutProvider from "./lib/context/AdminLayoutContext";
import AuthProvider from "@/app/lib/context/AuthContext";
import ExaminationsProvider from "@/app/lib/context/ExaminationsContext";
import NoticesProvider from "@/app/lib/context/NoticesContext";
import SubjectsProvider from "@/app/lib/context/SubjectsContext";
import StudyAreasProvider from "@/app/lib/context/StudyAreasContext";
import ExamsProvider from "./lib/context/ExamsContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AdminLayoutProvider>
          <AuthProvider>
            <StudyAreasProvider>
              <SubjectsProvider>
                <ExaminationsProvider>
                  <ExamsProvider>
                    <NoticesProvider>
                      {children}
                    </NoticesProvider>
                  </ExamsProvider>
                </ExaminationsProvider>
              </SubjectsProvider>
            </StudyAreasProvider>
          </AuthProvider>
        </AdminLayoutProvider>
      </body>
    </html>
  );
}