import type { Metadata } from "next";
import { inter } from "./ui/fonts";
import AdminLayoutProvider from "./lib/context/AdminLayoutContext";
import AuthProvider from "@/app/lib/context/AuthContext";
import ExaminationsProvider from "@/app/lib/context/ExaminationsContext";
import NavigationProvider from "@/app/lib/context/NavigationContext";
import NoticesProvider from "@/app/lib/context/NoticesContext";
import SubjectsProvider from "@/app/lib/context/SubjectsContext";
import StudyAreasProvider from "@/app/lib/context/StudyAreasContext"; // Import missing
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AdminLayoutProvider>
          <NavigationProvider>
            <AuthProvider>
              <StudyAreasProvider>
                <SubjectsProvider>
                  <ExaminationsProvider>
                    <NoticesProvider>
                        {children}
                    </NoticesProvider>
                  </ExaminationsProvider>
                </SubjectsProvider>
              </StudyAreasProvider>
            </AuthProvider>
          </NavigationProvider>
        </AdminLayoutProvider>
      </body>
    </html>
  );
}